#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/sing-box
CONF=/etc/sing-box/config.json

start_service() {
    [ -f "$CONF" ] || return 1
    procd_open_instance sing-box
    procd_set_param command $PROG run -c $CONF
    procd_set_param respawn
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 sing-box 2>/dev/null || true
}
